repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        name: ruff lint
        args: [--fix]
      - id: ruff-format
        name: ruff format
        args: []
  
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.16.0
    hooks:
      - id: cspell
        name: cspell
        args: [--no-progress]
        files: \.(py|cpp|h|md)$
        exclude: ^(cpp/Blackmagic|\.venv|__pycache__|build|dist|\.memories|docs|sandbox)/
